### ISSUE TITLE
Onboard Nicole

### ISSUE THREAD

**Issue by tim-schilling** [DEFNA/foundation#9]
See [DjangoCon US setup instructions](https://github.com/djangocon/djangocon-us-docs/blob/master/howtos/new-team-member.md)

- [x] Add to Slack
- [x] Google Apps:
    - [x] Create @defna.org email address
    - [x] Add email to hello@defna.org
- [x] Add to Google Drive (@adamfast)
- [x] GitHub (@adamfast)
  - [x] Add to [DjangoCon](https://github.com/djangocon) Organization (if not already a member)
  - [x] Add to [DEFNA](https://github.com/DEFNA) Organization 
  - [x] Add to [Board Team](https://github.com/orgs/DEFNA/teams/board)
- [x] Add to 1password (@adamfast)
- [x] Add to [defna.org](https://github.com/DEFNA/defna.org) website (https://github.com/DEFNA/defna.org/pull/51)
    - [x] Add bio
    - [x] Add photo
    - [x] Blog about addition (can be part of our board updates about officers too)

**Comment by tim-schilling** [comment]
@sodevious can you confirm the above steps have been completed and this can be closed?

**Comment by sodevious** [comment]
@tim-schilling confirmed!
